export interface InputProps {
    initialValue: string,
    length: number,
    type: string,
    onComplete: (activeGroup: string) => void,
    validate: (activeGroup: string) => void,
    secret: boolean,
    disabled: boolean,
    focus: boolean,
    onChange: (activeGroup: string) => void,
    inputMode: string,
    style: object, 
    inputStyle: object, 
    inputFocusStyle: object,
    autoSelect: object,
    regexCriteria: object,
  }
//   initialValue = '',
//     type = 'numeric',
//     secret = false,
//     validate = null,
//     focus = false,
//     disabled = false,
//     onChange = () => {},
//     onComplete = () => {},
//     inputMode = undefined,
//     style = {},
//     inputStyle = {},
//     inputFocusStyle = {},
//     autoSelect = true,
//     regexCriteria =  /^[a-zA-Z0-9]+$/,

  export interface InputItemProps {
    initialValue:string,
    onChange:(activeGroup: string) => void,
    onBackspace:(activeGroup: string) => void,
    onPaste: (activeGroup: string) => void,
    secret: boolean,
    disabled: boolean,
    type: string,
    inputMode: string,
    validation: boolean,
    inputStyle: object, 
    inputFocusStyle:object,
    autoSelect: boolean,
    regexCriteria: string,
  }
